org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:G1NewCollectionHeuristicPercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=100
android.useAndroidX=true
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
kotlin.daemon.jvmargs=-Xmx2G
org.gradle.workers.max=4
org.gradle.parallel=true
org.gradle.caching=true
